#!/usr/bin/env python

import platform
import socket
import os

build_number = os.environ.get('BUILD_NUMBER')
build_host = os.environ.get('NODE_NAME')
build_url = os.environ.get('BUILD_URL')
git_url = os.environ.get('GIT_URL')
git_branch = os.environ.get('GIT_BRANCH')
git_commit = os.environ.get('GIT_COMMIT')
git_short = os.environ.get('GIT_SHORT')

print "Hostname is " + socket.getfqdn()
print "Linux Distribution is " + platform.linux_distribution()[0]
print "Linux Dist Release is " + platform.linux_distribution()[1]
print "Python version is " + platform.python_version()
if build_number:
    print "Build number is " + build_number 
if build_host:
    print "Built on host " + build_host 
if build_url:
    print "Build URL is " + build_url 
if git_url:
    print "Git URL is " + git_url 
if git_branch:
    print "Git branch is " + git_branch 
if git_commit:
    print "Git SHA is " + git_commit 
if git_short:
    print "Git short SHA is " + git_short 
print "Deployed as " + os.environ.get('USER')
